### ISSUE TITLE
`kevm foundry-show test` failed

### ISSUE THREAD

**Issue by fyang1024** [runtimeverification/evm-semantics#1779] opened 2023-04-26 12:14 UTC
kevm version: 

> v1.0.126

commit:  

> 79530db  "Proof digests for better rebuilding (#1755) *..."

the issue:

> the [calculated proof file name ](https://github.com/runtimeverification/evm-semantics/blob/79530db735032977b0834b2d237fdf4fcd3320e0/kevm-pyk/src/kevm_pyk/foundry.py#L99) does not match the proof file generated by [`pyk.proof.proof`](https://github.com/runtimeverification/pyk/blob/1bd637d95b92803f212d96109b459af31456bc09/src/pyk/proof/proof.py#L38)

the error message:

> File "/nix/store/35mk26r5cqzns4zwxnxyy6n6f1hhkiis-python3.10-pyk-0.1.265/lib/python3.10/site-packages/pyk/proof/reachability.py", line 46, in read_proof
>     raise ValueError(f'Could not load APRProof from file {id}: {proof_path}')
> ValueError: Could not load APRProof from file ...

steps to reproduce:

> ```sh
> $ cd tests/foundry
> $ forge build
> ```
> 
> ```sh
> $ kevm foundry-kompile
> ```
> 
> ```sh
> $ kevm foundry-prove --test AssertTest.test_assert_true
> ```
> 
> ```sh
> $ kevm foundry-show AssertTest.test_assert_true
> ```

**Comment by anvacaru** [comment] 2023-05-16 16:17
I'm sorry for not getting back to you sooner. I could not reproduce this issue, but it may have been fixed since. I'll close this for now. Please reopen if the problem persists.

**Closed by anvacaru** 2023-05-16 16:17 UTC
