### ISSUE TITLE
Manual `preserves-definedness` attribute on rules

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/evm-semantics#1857] opened 2023-05-25 16:24 UTC
The booster backend relies on `preserves-definedness` attribute to be able to continue execution in a lot of places. We should have either (i) stronger analysis of definedness which can detect that these rules are preserving it, or (ii) refactor KEVM to make it obvious that the rules do preserve definedness.

See: https://github.com/runtimeverification/evm-semantics/pull/1848

**Comment by jberthold** [comment] 2023-05-25 23:53
Agree this is suboptimal. We should always prefer marking functions `total` to marking rules `preserve-definedness`.
The problem is that some rules use partial functions on the RHS but ensure definedness via side conditions.
Where we used `preserves-definedness` here, we know the RHS functions are only called on arguments on which they are defined - which requires individual analysis of each function and function call.

**Comment by anvacaru** [comment] 2024-01-31 19:07
We're opening PRs in which we add the `[preserves-definedness]` attribute on an as-needed basis. I'm closing this for now.

**Closed by anvacaru** 2024-01-31 19:07 UTC
Labels: low priority
