### ISSUE TITLE
Set default version of Python to 3.11

### ISSUE THREAD

**Issue by ehildenb** [runtimeverification/evm-semantics#1693] opened 2023-04-04 21:58 UTC
Python3.11 has some advantages for us:

- It doesn't cause a segfault on some user-supplied inputs when loading Kore terms from the backend to Kast format in the frontend with the recursion limit set higher.
- It's noticeably faster at translating Kast <-> Kore.

Can we set it up so that Python3.11 is the default at least for the `kup` installed KEVM? For not-`kup` installs, we can just put a note in the README saying that users should consider upgrading their python.

- [ ] Python3.11 default in Nix package.
- [ ] Note in README telling user to upgrade to python 3.11.

**Comment by tothtamas28** [comment] 2023-04-05 10:07
> It's noticeably faster at translating Kast <-> Kore

I did some profiling for KAST-to-KORE (https://github.com/runtimeverification/pyk/pull/332): [profile.zip](https://github.com/runtimeverification/evm-semantics/files/11157569/profile.zip)


| pyk ver. | Python ver. | Load KAST | Parse KORE | KAST-to-KORE (1st) | KAST-to-KORE (2nd) |
|----------|-------------|-----------|------------|--------------------|--------------------|
|  0.1.212 |      3.8.16 |     3.966 |     31.549 |              0.124 |              0.021 |
|  0.1.212 |      3.11.2 |     3.587 |     34.832 |              0.123 |              0.023 |
|  0.1.218 |      3.8.16 |     3.480 | **13.131** |          **0.114** |          **0.018** |
|  0.1.218 |      3.11.2 | **3.191** |     16.173 |              0.125 |              0.021 |

For KAST-to-KORE, there doesn't seem to be a significant performance increase from Python 3.8 and 3.11. On the other hand, pyk performance improved noticeably for related code since version 0.1.212. Are you sure you're not measuring the effects of that (e.g. #1674)?

**Comment by tothtamas28** [comment] 2023-04-05 10:15
> It doesn't cause a segfault on some user-supplied inputs

Can the segfault be reproduced on `3.10` (for https://github.com/runtimeverification/pyk/issues/286 I couldn't)? Project `kevm-pyk` already specifies that as the lower bound, so if it turn's out there is no significant performance benefit of 3.11, maybe the solution would be to prioritize https://github.com/runtimeverification/pyk/issues/135.

**Comment by ehildenb** [comment] 2023-04-05 14:05
I was using Python3.10.6, and it was still segfaulting. I could not figure out how to get python3.10.10 installed easily, which I believe is the version you tried.

**Comment by ehildenb** [comment] 2023-04-05 14:14
Ok, updating to python3.11 doesn't yield as much benefit on `master` pyk as I thought: 
![image](https://user-images.githubusercontent.com/12721972/230108151-2a668273-1939-4589-a556-12bfa1bd38f7.png)

Also no segfault on python3.10.6, so I need to figure out why it's segfaulting on our client's machine then.... I will create a docker image for them directly, see if that fixes it.

**Comment by ehildenb** [comment] 2023-04-05 14:17
Let's prioritize the bump to python 3.10 though I think, if it's easy. Not sure what that requires though, the default Ubuntu python is not 3.10 is it?

**Comment by tothtamas28** [comment] 2023-04-05 14:27
> Not sure what that requires though, the default Ubuntu python is not 3.10 is it?

On Ubuntu Jammy it is. On Focal, it's 3.8.

> I was using Python3.10.6, and it was still segfaulting.

Maybe it's not really about Python version but rather system Python vs non-system Python then. (The interpreter that reproduced the error for me was system Python, whereas the other ones were `pyenv` installed.)

**Comment by palinatolmach** [comment] 2023-07-26 17:48
@tothtamas28 did we update the Python version in KEVM? Can we close this issue?

**Comment by tothtamas28** [comment] 2023-07-26 17:51
> did we update the Python version in KEVM? Can we close this issue?

We updated to 3.10, this issue can be closed as not planned.

**Closed** 2023-07-26 17:55 UTC
