### ISSUE TITLE
Concrete rules ambiguity

### ISSUE THREAD

**Issue by anvacaru** [runtimeverification/evm-semantics#1634] opened 2023-03-16 06:19 UTC
In both the [concrete-rules.txt](https://github.com/runtimeverification/evm-semantics/blob/d597e7a7730f46eaea357188c3dbe7bb3177fc36/tests/specs/concrete-rules.txt#L28) and [kevm.py](https://github.com/runtimeverification/evm-semantics/blob/d597e7a7730f46eaea357188c3dbe7bb3177fc36/kevm-pyk/src/kevm_pyk/kevm.py#L183) there is a label named `EVM-TYPES.Bytes.range` which I can't find in the source files which leads to the following questions:

1) Kompile should have warnings emitted for each lemma in the concrete rules which is not found. Are any warnings emitted?
2) Still, there are rules in our codebase that use the `[concrete]`. Is there a reason for this?
3) Could we remove the hardcoded list from `kevm.py` and read the list from `concrete-rules.txt`?

**Comment by anvacaru** [comment] 2023-03-16 06:51
For 3. is there a reason to have the `concrete-rules.txt` under `tests/specs`? Could we use something in python like `return open(filename).read().splitlines()` to avoid duplication?

**Comment by ehildenb** [comment] 2023-03-16 14:26
Are you able to confirm with a minimal example that the concrete-rule is not actually in the definition, but kmopile does not give a warning? If so, let's open an issue for that one against K repo, with the minimal example.

And actually, I want to move the other direction, remove the `concrete-rules.txt` instead, because I want to move all the logic into Python. We have it set so that by default you get the pyk kompile: https://github.com/runtimeverification/evm-semantics/pull/1616. So we're really just keeping around the Bash compile "just in case" at this point.

**Comment by ehildenb** [comment] 2023-03-27 17:17
Todo:

- Minimal example in the frontend for `kompile --backend haskell --concrete-rules MODULE-THAT-EXISTS.rule-that-doesnt-exist`, and add as a test and error to th efrontend.
- Once that is merged, remove the offending rules from `kevm.py` in this repo.
- Also remove the now unused `concrete-rules.txt` in this repo.

**Comment by Scott-Guest** [comment] 2023-03-30 23:28
The following labels do not have corresponding rules (as confirmed by both grep and the error check I added):

- EVM-TYPES.#asByteStack
- EVM-TYPES.#asByteStackAux.recursive
- EVM-TYPES.#asWord.recursive
- EVM-TYPES.#padRightToWidth
- EVM-TYPES.#padToWidth
- EVM-TYPES.#range
- EVM-TYPES.Bytes.range
- EVM-TYPES.mapWriteBytes.recursive

**Closed** 2023-04-03 16:42 UTC
